/* GitHub Pages client engine: replaces the Node persistence/API layer with browser storage. */
(() => {
  'use strict';
  const MLB = 'https://statsapi.mlb.com/api';
  const SEASON = new Date().getFullYear();
  const GAME_TYPES = 'F,D,L,W';
  const START = `${SEASON}-09-20`, END = `${SEASON}-11-20`;
  const STORAGE = `playoff-fantasy:${SEASON}`;
  const SCORING = {
    batting:{H:.5,'1B':1,'2B':2,'3B':3,HR:4,R:2,RBI:2,BB:1,IBB:1,SO:-.25,HBP:1,SF:1,SH:1,GIDP:-.5,SB:2,CS:-1,GS:1,GWRBI:1},
    pitching:{W:5,L:-5,SV:5,HLD:3,BS:-3,IP:3,ER:-.5,BB:-.5,IBB:-.5,HBP:-.5,BK:-.5,SO:1,PK:1,CG:2,SHO:2,NH:5,PG:10}
  };
  const sleep = ms => new Promise(r=>setTimeout(r,ms));
  const num = v => Number.isFinite(Number(v)) ? Number(v) : 0;
  const round = x => Math.round(x*1e6)/1e6;
  const outsFromIP = ip => { const [w,f='0']=String(ip??'0').split('.'); return num(w)*3+num(f); };
  const fold = s => String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const todayET = () => new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date());

  const load = () => { try { return JSON.parse(localStorage.getItem(STORAGE)||'{}'); } catch { return {}; } };
  let db = load();
  if (!Array.isArray(db.teams)) db.teams=[];
  if (!db.records || typeof db.records!=='object') db.records={};
  if (!db.pool || typeof db.pool!=='object') db.pool={};
  let schedule=[], eliminated=new Set(), teams={}, lastCheckedAt=null, lastError=null, version=1;

  function save(){ try { localStorage.setItem(STORAGE,JSON.stringify(db)); } catch(e){ throw new Error('Browser storage is full. Clear old tracker data and refresh.'); } }
  async function syncTeamsFromCloud(){ const rows=await window.SupabaseFantasy.getTeams(); db.teams=rows.map(r=>({id:r.id,name:r.name,owner:r.owner||'',playerIds:Array.isArray(r.player_ids)?r.player_ids.map(Number):[]})); db.version=(db.version||1)+1; save(); }
  async function syncHistoryFromCloud(){
    try {
      const rows=await window.SupabaseFantasy.getGameRecords(SEASON);
      for(const row of rows||[]){
        const cloud=row.record;
        if(!cloud?.gamePk) continue;
        const local=db.records[cloud.gamePk];
        if(!local || cloud.final || !local.final) db.records[cloud.gamePk]=cloud;
      }
    } catch(err) { console.warn('Cloud history unavailable; using local history.',err); }
  }
  async function persistFinalRecord(record){
    if(!record?.final || !window.SupabaseFantasy.isSignedIn()) return;
    try { await window.SupabaseFantasy.upsertGameRecord(record,SEASON); }
    catch(err){ console.warn(`Could not save final game ${record.gamePk} to cloud history.`,err); }
  }
  function requireAdmin(){ if(!window.SupabaseFantasy.isSignedIn()) throw new Error('Sign in as a league admin to make changes.'); }
  async function getJson(url){ let last; for(let i=0;i<3;i++){ try { const r=await fetch(url,{cache:'no-store'}); if(!r.ok) throw new Error(`MLB API HTTP ${r.status}`); return await r.json(); } catch(e){ last=e; if(i<2) await sleep(400*(i+1)); } } throw last; }
  function normalizeTeam(side){ const t=side.team||{}; return {id:t.id,name:t.name,abbr:t.abbreviation||t.teamCode||(t.name?t.name.split(' ').pop().slice(0,3).toUpperCase():'?'),score:side.score,isWinner:side.isWinner}; }
  function normalizeGame(g){ const s=g.seriesStatus; return {gamePk:g.gamePk,date:g.officialDate||String(g.gameDate).slice(0,10),startTime:g.gameDate,gameType:g.gameType,series:g.seriesDescription,gameNumber:g.seriesGameNumber,gamesInSeries:g.gamesInSeries,state:g.status?.abstractGameState,detail:g.status?.detailedState,away:normalizeTeam(g.teams.away),home:normalizeTeam(g.teams.home),inning:g.linescore?.currentInningOrdinal,inningState:g.linescore?.inningState,seriesStatus:s?{isOver:Boolean(s.isOver),losingTeamId:s.losingTeam?.id,description:s.shortDescription||s.description}:null}; }
  async function getSchedule(){ const qs=new URLSearchParams({sportId:'1',gameType:GAME_TYPES,season:String(SEASON),startDate:START,endDate:END,hydrate:'team,linescore'}); const d=await getJson(`${MLB}/v1/schedule?${qs}`); return (d.dates||[]).flatMap(x=>x.games||[]).filter(g=>!['Postponed','Cancelled'].includes(g.status?.detailedState)).map(normalizeGame); }
  function battingLine(b){ const h=num(b.hits),d=num(b.doubles),t=num(b.triples),hr=num(b.homeRuns); return {H:h,'1B':Math.max(0,h-d-t-hr),'2B':d,'3B':t,HR:hr,R:num(b.runs),RBI:num(b.rbi),BB:num(b.baseOnBalls),IBB:num(b.intentionalWalks),SO:num(b.strikeOuts),HBP:num(b.hitByPitch),SF:num(b.sacFlies),SH:num(b.sacBunts),GIDP:num(b.groundIntoDoublePlay),SB:num(b.stolenBases),CS:num(b.caughtStealing),GS:0,GWRBI:0}; }
  function hasBatting(b){ return num(b.plateAppearances)>0||num(b.atBats)>0||num(b.runs)>0||num(b.stolenBases)>0||num(b.caughtStealing)>0; }
  function pitchingLine(p,ctx){ const outs=p.outs!=null?num(p.outs):outsFromIP(p.inningsPitched); const l={W:num(p.wins),L:num(p.losses),SV:num(p.saves),HLD:num(p.holds),BS:num(p.blownSaves),OUTS:outs,ER:num(p.earnedRuns),BB:num(p.baseOnBalls),IBB:num(p.intentionalWalks),HBP:num(p.hitBatsmen),BK:num(p.balks),SO:num(p.strikeOuts),PK:num(p.pickoffs),CG:num(p.completeGames),SHO:num(p.shutouts),NH:0,PG:0}; if(l.CG>=1&&num(p.hits)===0&&outs>=27){l.NH=1; if(l.BB===0&&l.HBP===0&&num(p.battersFaced)===27&&ctx.teamErrors===0&&ctx.opponentLeftOnBase===0) l.PG=1;} return l; }
  function hasPitching(p){ return num(p.outs)>0||num(p.battersFaced)>0||outsFromIP(p.inningsPitched)>0; }
  function analyze(pbp,isFinal){ const plays=pbp?.allPlays||[], gs={}, scored=plays.filter(p=>p.result?.awayScore!=null&&p.result?.homeScore!=null&&p.about?.isComplete!==false); let gwr=null; for(const p of plays){const id=p.matchup?.batter?.id;if(p.result?.eventType==='home_run'&&num(p.result.rbi)===4&&id) gs[id]=(gs[id]||0)+1;} if(isFinal&&scored.length){const last=scored.at(-1).result,w=num(last.awayScore)>num(last.homeScore)?'away':num(last.homeScore)>num(last.awayScore)?'home':null;if(w){const diff=r=>w==='away'?num(r.awayScore)-num(r.homeScore):num(r.homeScore)-num(r.awayScore);let before=0,c=null;for(const p of scored){const after=diff(p.result);if(after<=0)c=null;else if(before<=0)c=p;before=after;}if(c&&num(c.result.rbi)>0&&c.matchup?.batter)gwr=c.matchup.batter.id;}} return {grandSlams:gs,gwrbiBatter:gwr}; }
  function buildRecord(meta,box,pbp,isFinal){ const {grandSlams,gwrbiBatter}=analyze(pbp,isFinal), players={}; for(const key of ['away','home']){const opp=key==='away'?'home':'away',side=box.teams?.[key];if(!side)continue;const teamId=side.team?.id,oppId=box.teams?.[opp]?.team?.id,ctx={teamErrors:num(side.teamStats?.fielding?.errors),opponentLeftOnBase:num(box.teams?.[opp]?.teamStats?.batting?.leftOnBase)};for(const e of Object.values(side.players||{})){const id=e.person?.id;if(!id)continue;const s=e.stats||{},bat=s.batting&&hasBatting(s.batting)?battingLine(s.batting):null,pit=s.pitching&&hasPitching(s.pitching)?pitchingLine(s.pitching,ctx):null;if(!bat&&!pit)continue;if(bat){bat.GS=grandSlams[id]||0;bat.GWRBI=gwrbiBatter===id?1:0;}players[id]={id,name:e.person.fullName,pos:e.position?.abbreviation,teamId,oppId,batting:bat,pitching:pit};}} return {gamePk:meta.gamePk,date:meta.date,startTime:meta.startTime,series:meta.series,final:Boolean(isFinal),awayId:meta.away.id,homeId:meta.home.id,players}; }
  function scoreLine(line,table){let total=0,parts={};for(const [k,w] of Object.entries(table)){const c=k==='IP'?(line.OUTS||0)/3:(line[k]||0);if(!c)continue;const p=round(c*w);parts[k]={count:round(c),points:p};total+=p;}return {total:round(total),parts};}
  function computeEliminated(games){const out=new Set();for(const g of games){if(g.seriesStatus?.isOver&&g.seriesStatus.losingTeamId)out.add(g.seriesStatus.losingTeamId);}const series=new Map();for(const g of games){if(g.state!=='Final'||!g.gamesInSeries)continue;const key=`${g.series}|${[g.away.id,g.home.id].sort((a,b)=>a-b).join('-')}`;if(!series.has(key))series.set(key,{need:Math.floor(g.gamesInSeries/2)+1,wins:new Map(),teams:[g.away.id,g.home.id]});const e=series.get(key);const winner=g.away.isWinner?g.away.id:g.home.isWinner?g.home.id:(g.away.score!=null&&g.home.score!=null&&g.away.score!==g.home.score?(g.away.score>g.home.score?g.away.id:g.home.id):null);if(winner)e.wins.set(winner,(e.wins.get(winner)||0)+1);}for(const e of series.values())for(const [id,w] of e.wins)if(w>=e.need){const loser=e.teams.find(x=>x!==id);if(loser)out.add(loser);}return out;}
  function aggregate(){const m=new Map(), today=todayET();for(const rec of Object.values(db.records)){for(const p of Object.values(rec.players||{})){let a=m.get(p.id);if(!a)a={id:p.id,name:p.name,pos:p.pos,teamId:p.teamId,latest:'',total:0,hitting:0,pitching:0,today:0,games:[]};const bat=p.batting?{line:p.batting,...scoreLine(p.batting,SCORING.batting)}:null,pit=p.pitching?{line:p.pitching,...scoreLine(p.pitching,SCORING.pitching)}:null,gt=(bat?.total||0)+(pit?.total||0);a.games.push({gamePk:rec.gamePk,date:rec.date,startTime:rec.startTime,final:rec.final,oppId:p.oppId,total:round(gt),batting:bat,pitching:pit});a.hitting+=bat?.total||0;a.pitching+=pit?.total||0;a.total+=gt;if(rec.date===today)a.today+=gt;if((rec.startTime||'')>=a.latest){a.latest=rec.startTime||'';a.teamId=p.teamId;if(p.pos)a.pos=p.pos;}m.set(p.id,a);}}for(const a of m.values()){a.games.sort((x,y)=>String(x.startTime).localeCompare(String(y.startTime)));a.total=round(a.total);a.hitting=round(a.hitting);a.pitching=round(a.pitching);a.today=round(a.today);}return m;}
  function teamLabel(id){return teams[id]?.abbr||'';}
  const liveTeamIds=()=>new Set(schedule.filter(g=>g.state==='Live').flatMap(g=>[g.away.id,g.home.id]));
  function playerView(id,agg){const a=agg.get(id),b=a||db.pool[id]||{id,name:`Player ${id}`},teamId=a?a.teamId:b.teamId;return {id,name:b.name,pos:b.pos||'',teamId,team:teamLabel(teamId),eliminated:teamId!=null&&eliminated.has(teamId),live:teamId!=null&&liveTeamIds().has(teamId),total:a?.total||0,hitting:a?.hitting||0,pitching:a?.pitching||0,today:a?.today||0,games:a?.games.length||0};}
  function state(){const agg=aggregate();const ts=db.teams.map(t=>{const players=t.playerIds.map(id=>playerView(id,agg)).sort((a,b)=>b.total-a.total||a.name.localeCompare(b.name)),total=players.reduce((s,p)=>s+p.total,0),today=players.reduce((s,p)=>s+p.today,0);return {id:t.id,name:t.name,owner:t.owner,total:round(total),today:round(today),alive:players.filter(p=>!p.eliminated).length,players};}).sort((a,b)=>b.total-a.total||a.name.localeCompare(b.name));ts.forEach((t,i)=>t.rank=i&&ts[i-1].total===t.total?ts[i-1].rank:i+1);return {version:`${version}.${db.version||1}`,checkedAt:lastCheckedAt,error:lastError,live:schedule.some(g=>g.state==='Live'),today:todayET(),teams:ts,games:schedule.map(g=>({gamePk:g.gamePk,date:g.date,startTime:g.startTime,series:g.series,gameNumber:g.gameNumber,gamesInSeries:g.gamesInSeries,state:g.state,detail:g.detail,inning:g.inning,inningState:g.inningState,away:{abbr:g.away.abbr,name:g.away.name,score:g.away.score,out:eliminated.has(g.away.id)},home:{abbr:g.home.abbr,name:g.home.name,score:g.home.score,out:eliminated.has(g.home.id)}})),eliminated:[...eliminated].map(id=>teams[id]?.abbr).filter(Boolean),scoring:SCORING,season:SEASON,gameTypes:GAME_TYPES,adminRequired:true};}
  async function resolveMissing(){const need=[...new Set(db.teams.flatMap(t=>t.playerIds))].filter(id=>!db.pool[id]);for(let i=0;i<need.length;i+=50){const chunk=need.slice(i,i+50);try{const d=await getJson(`${MLB}/v1/people?personIds=${chunk.join(',')}&hydrate=currentTeam`);for(const p of d.people||[])db.pool[p.id]={id:p.id,name:p.fullName,pos:p.primaryPosition?.abbreviation,teamId:p.currentTeam?.id};}catch(e){}}}
  async function refresh(){try{await syncTeamsFromCloud();await syncHistoryFromCloud();schedule=await getSchedule();teams={};for(const g of schedule)for(const s of [g.away,g.home])teams[s.id]={id:s.id,name:s.name,abbr:s.abbr};eliminated=computeEliminated(schedule);const due=schedule.filter(g=>g.state==='Live'||!db.records[g.gamePk]||(g.state==='Final'&&!db.records[g.gamePk].final));for(let i=0;i<due.length;i+=3){await Promise.all(due.slice(i,i+3).map(async g=>{try{const [box,pbp]=await Promise.all([getJson(`${MLB}/v1/game/${g.gamePk}/boxscore`),getJson(`${MLB}/v1/game/${g.gamePk}/playByPlay`).catch(()=>null)]);const record=Object.assign(buildRecord(g,box,pbp,g.state==='Final'&&!!pbp),{fetchedAt:Date.now()});db.records[g.gamePk]=record;if(record.final)await persistFinalRecord(record);}catch(e){lastError=`Game ${g.gamePk}: ${e.message}`;}}));}const ids=[...new Set(schedule.flatMap(g=>[g.away.id,g.home.id]))];for(const id of ids){try{const d=await getJson(`${MLB}/v1/teams/${id}/roster?rosterType=active&season=${SEASON}`);for(const r of d.roster||[])db.pool[r.person.id]={id:r.person.id,name:r.person.fullName,pos:r.position?.abbreviation,teamId:id};}catch(e){}}await resolveMissing();if(window.SupabaseFantasy.isSignedIn()){for(const rec of Object.values(db.records))if(rec?.final)await persistFinalRecord(rec);}db.version=(db.version||1)+1;save();lastCheckedAt=new Date().toISOString();lastError=null;version++;return state();}catch(e){lastError=e.message;throw e;}}
  let refreshPending = null;
  function refreshShared(){
    if(!refreshPending) refreshPending=refresh().catch(e=>{console.error('Tracker data refresh failed:',e);}).finally(()=>{refreshPending=null;});
    return refreshPending;
  }
  function search(q,limit=25){const agg=aggregate(),needle=fold(q);const ids=new Set([...Object.keys(db.pool).map(Number),...agg.keys()]);return [...ids].map(id=>playerView(id,agg)).filter(p=>!needle||fold(p.name).includes(needle)).sort((a,b)=>(b.total-a.total)||a.name.localeCompare(b.name)).slice(0,limit);}
  function detail(id){const a=aggregate().get(Number(id));if(!a&&!db.pool[id])throw new Error('Player not found.');const p=playerView(Number(id),a?new Map([[Number(id),a]]):new Map());p.games=a?.games||[];return p;}
  function team(id){const t=db.teams.find(x=>x.id===id);if(!t)throw new Error('Team not found.');return t;}
  async function api(path,opts={}){const method=(opts.method||'GET').toUpperCase();const parts=path.split('?')[0].split('/').filter(Boolean);const body=opts.body?JSON.parse(opts.body):{};if(path==='/api/state'){await refreshShared();return state();}if(parts[1]==='players'&&method==='GET'&&parts.length===2){const q=new URLSearchParams(path.split('?')[1]||'');return Promise.resolve({players:search(q.get('q')||'',Number(q.get('limit')||25))});}if(parts[1]==='players'&&parts.length===3)return Promise.resolve(detail(Number(parts[2])));if(parts[1]==='refresh')return refresh().then(()=>({ok:true,checkedAt:lastCheckedAt,error:lastError}));if(parts[1]==='teams'&&parts.length===2&&method==='POST'){requireAdmin();const name=String(body.name||'').trim();const owner=String(body.owner||'').trim().slice(0,60);if(!name)throw new Error('Team name is required.');const t=await window.SupabaseFantasy.createTeam({name,owner,player_ids:[]});await syncTeamsFromCloud();return t;}if(parts[1]==='teams'&&parts.length===3&&method==='PATCH'){requireAdmin();const t=team(parts[2]);const name=String(body.name||'').trim();const owner=String(body.owner||'').trim().slice(0,60);if(!name)throw new Error('Team name is required.');const out=await window.SupabaseFantasy.updateTeam(t.id,{name,owner});await syncTeamsFromCloud();return out;}if(parts[1]==='teams'&&parts.length===3&&method==='DELETE'){requireAdmin();team(parts[2]);await window.SupabaseFantasy.deleteTeam(parts[2]);await syncTeamsFromCloud();return {ok:true};}if(parts[1]==='teams'&&parts.length===4&&parts[3]==='players'&&method==='POST'){requireAdmin();const t=team(parts[2]),id=Number(body.playerId);if(!db.pool[id])throw new Error('Unknown player. Refresh the player pool first.');if(t.playerIds.includes(id))throw new Error('That player is already on this team.');const owner=db.teams.find(x=>x.id!==t.id&&x.playerIds.includes(id));if(owner)throw new Error(`That player is already on ${owner.name}.`);const out=await window.SupabaseFantasy.updateTeam(t.id,{player_ids:[...t.playerIds,id]});await syncTeamsFromCloud();return out;}if(parts[1]==='teams'&&parts.length===5&&parts[3]==='players'&&method==='DELETE'){requireAdmin();const t=team(parts[2]),id=Number(parts[4]);if(!t.playerIds.includes(id))throw new Error('That player is not on this team.');const out=await window.SupabaseFantasy.updateTeam(t.id,{player_ids:t.playerIds.filter(x=>x!==id)});await syncTeamsFromCloud();return out;}return Promise.reject(new Error(`Unsupported client route: ${path}`));}
  window.PlayoffFantasy={api,refresh,state,reset(){localStorage.removeItem(STORAGE);location.reload();},season:SEASON};
})();
